# Generated by Django 3.2.16 on 2023-01-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=80)),
                ('email', models.CharField(default='', max_length=80)),
                ('subject', models.CharField(default='', max_length=150)),
                ('message', models.CharField(default='', max_length=3600)),
            ],
        ),
    ]
